apiVersion: v1
kind: Secret
metadata:
  name: jenkins-github-oauth-secret
  labels:
    "carthago.cloud/jenkinsauthentication": "authentication"
stringData:
  # Secret for local tests
  # Homepage =          http://localhost:8080
  # Auth callback url = http://localhost:8080/securityRealm/finishLogin
  # Prod uses secrets with the same name
  clientID: e4fe7785ccabf2f7ae28
  clientSecret: 04194362b8269617b790874574c3ade081a422b7
