apiVersion: v1
kind: Secret
metadata:
  name: jenkins-github-auth-secret
  namespace: scala3-community-build
  labels:
    "operator-service.com/jenkinsauthentication" : "jenkins-github-oauth"
stringData:
  # Secret for local tests 
  # Homepage =          http://localhost:8080
  # Auth callback url = http://localhost:8080/securityRealm/finishLogin
  clientSecret: 04194362b8269617b790874574c3ade081a422b7