name: "Push raport to gh-pages"
description: "Used to push a raport file to the gh-pages branch for the webiste to be updated"
inputs:
  artifact-name:
    description: "Name of the artifact that has been uploaded"
    required: true
  file-to-pick:
    description: "Name of the file that has been uploaded and should be picked for the raport"
    required: true
  build-title:
    description: "Title of the post file that will be created"
    required: true
  token:
    description: "Token for pushing"
    required: true

runs:
  using: "composite"
  steps:
    - name: Git Checkout
      uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: ~/

    - name: Add front matter to the file
      shell: bash
      run: ./scripts/insert_post_front_matter.sh ~/${{ inputs.file-to-pick }} ${{ inputs.build-title }}

    - name: Git Checkout
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        token: ${{ inputs.token }}

    - name: Exit if artifact file is empty
      shell: bash
      run: |
        if [ ! -s ~/${{ inputs.file-to-pick }} ]; then
          echo "::warning title=GH page upload failure::The input file ${{ inputs.file-to-pick }} is empty" 
          exit 0
        fi
    - name: Add the raport to _post dir and push
      shell: bash
      run: |
        # Get filename in lowercase kebab-case
        normalized_build_title="$(echo '${{ inputs.build-title }}' | tr '[:upper:]' '[:lower:]' | tr ' ' '-')"
        filename="$(date -u '+%Y-%m-%d')-$normalized_build_title.md"

        # create _posts dir if not exists
        mkdir -p "./_posts"

        # Find raport from same compiler version
        same_ver_pattern=".*-$normalized_build_title\.md"

        # Find first match
        file_path=$(find "./_posts" -type f -regex "$same_ver_pattern" -print -quit)

        # Check if a file was found and replace it
        if [[ -n "$file_path" ]]; then
          cat ~/${{ inputs.file-to-pick }} > $file_path
          if [[ $file_path != ./_posts/"$filename" ]]; then
            mv $file_path ./_posts/"$filename"
          fi
        else
          cat ~/${{ inputs.file-to-pick }} > ./_posts/"$filename"
        fi

        git config --global user.name "GitHub Actions"
        git config --global user.email "scala3-community-build@virtuslab.com"

        git add ./_posts/"$filename"
        git commit -m "Upload build raport: ${{ inputs.build-title }}"
        git push origin gh-pages

    - name: Git Checkout
      uses: actions/checkout@v3