apiVersion: batch/v1
kind: Job
metadata:
  name: compiler-builder-test
spec:
  template:
    spec:
      volumes:
      - name: mvn-repo-cert
        configMap:
          name: mvn-repo-cert
      containers:
      - name: compiler-builder-test
        image: virtuslab/scala-community-build-compiler-builder:test
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: mvn-repo-cert
          mountPath: /usr/local/share/ca-certificates/mvn-repo.crt
          subPath: mvn-repo.crt
          readOnly: true
        lifecycle:
          postStart:
            exec:
              command: ["update-ca-certificates"]
        command:
        - "bash"
        - "-c"
        - |
            (/build/build-revision.sh \
              https://github.com/lampepfl/dotty.git \
              3.1.0 \
              3.1.0-bin-COMMUNITY-SNAPSHOT \
              https://mvn-repo:8081/maven2/test \
            && echo \
            && echo "Compiler published successfully") || true
      restartPolicy: Never
  backoffLimit: 0
