apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvn-repo
spec:
  selector:
    matchLabels:
      app: mvn-repo
  template:
    metadata:
      labels:
        app: mvn-repo
    spec:
      volumes:
      - name: maven-data
        persistentVolumeClaim:
          claimName: maven-data
      containers:
      - name: mvn-repo
        image: communitybuild3/mvn-repo
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: maven-data
          mountPath: /mvn-repo/upload-dir
---
apiVersion: v1
kind: Service
metadata:
  name: mvn-repo
spec:
  type: ClusterIP
  selector:
    app: mvn-repo
  ports:
  - protocol: TCP
    port: 8081
