apiVersion: batch/v1
kind: Job
metadata:
  name: project-builder-sbt-test
spec:
  template:
    spec:
      containers:
        - name: project-builder-sbt-test
          image: virtuslab/scala-community-build-project-builder:jdk11-test
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 4G
          command:
            - "bash"
            - "-c"
            - |
              (/build/build-revision.sh \
                https://github.com/typelevel/shapeless-3.git \
                "v3.0.4" \
                3.1.0 \
                "" \
                "org.typelevel%shapeless3-deriving org.typelevel%shapeless3-test org.typelevel%shapeless3-typeable dummy.org%dummy-project" \
                https://mvn-repo:8081/maven2/test \
                1.5.5 \
                '{"sbt": {"commands": ["show crossScalaVersions", "show scalaVersion", "show scalacOptions"] }, "projects": {"exclude": ["dummy.org%dummy-.*"], "overrides": {"shapeless3-deriving": {"tests": "compile-only"}, "shapeless3-typeable": {"tests": "disabled"}} } }' \
                "" \
                "" \
              && echo \
              && echo "Community project published successfully") || true
      restartPolicy: Never
  backoffLimit: 0
