apiVersion: batch/v1
kind: Job
metadata:
  name: project-builder-mill-test
spec:
  template:
    spec:
      containers:
      - name: project-builder-mill-test
        image: virtuslab/scala-community-build-project-builder:jdk11-test
        imagePullPolicy: IfNotPresent
        command:
        - "bash"
        - "-c"
        - |
            (/build/build-revision.sh \
              https://github.com/com-lihaoyi/upickle.git \
              1.5.0 \
              3.1.0 \
              "" \
              "com.lihaoyi%ujson com.lihaoyi%upickle com.lihaoyi%upickle-core com.lihaoyi%upack com.lihaoyi%upickle-implicits dummy.org%dummy-project" \
              https://mvn-repo:8081/maven2/test \
              1.5.5 \
              '{"projects": {"exclude": ["dummy.org%dummy-.*"], "overrides": {"upickle-core": {"tests": "compile-only"}, "ujson": {"tests": "disabled"}} } }' \
              "" \
              "" \
            && echo \
            && echo "Community project published successfully") || true
      restartPolicy: Never
  backoffLimit: 0
