name: "Build projects"
description: "Used to build a project withing the Open cOmunityu Build"
inputs:
  project-name:
    description: "Name of the project to build"
    required: true
  scala-version:
    description: "Scala Version to use"
    required: true
runs:
  using: "composite"
  steps:
    - name: Check java version
      shell: bash
      run: |
        ls -l
        echo ""
        ls .github/workflows/
        ConfigFile=".github/workflows/buildConfig.json"
        DefaultJDK=11
        javaVersion=$(jq -r ".${{ inputs.project-name }}.config.java.version // ${DefaultJDK}" $ConfigFile)
        echo "java-version=$javaVersion" >> $GITHUB_ENV
        echo "JavaVersion set to $javaVersion"

    - name: Build
      uses: addnab/docker-run-action@v3
      with:
        image: "virtuslab/scala-community-build-project-builder:jdk${{ inputs.java-version }}-v0.1.2"
        options: -v ${{ github.workspace }}:/build/
        run: |
          ls -l /build/

          ConfigFile="/build/.github/workflows/buildConfig.json"
          function config() { jq -c -r ".${{ inputs.project-name }}$1" $ConfigFile }

          # echo "failure" > build-status.txt            

          /build/build-revision.sh \
              "$(config .repoUrl)" \
              "$(config .revision)" \
              "${{ inputs.scala-version }}" \
              '' \
              "$(config .targets)" \
              'https://repo1.maven.org/maven2' \
              '1.6.2' \
              "$(config .config)" 2>&1 | tee build-logs.txt

          ls -l /build/

    - name: Check results
      shell: bash
      run: ls -l
