name: "Build projects"
description: "Used to build a project withing the Open cOmunityu Build"
inputs:
  project-name:
    description: "Name of the project to build"
    required: true
  scala-version:
    description: "Scala Version to use"
    required: true
runs:
  using: "composite"
  steps:
    - name: Check java version
      shell: bash
      run: |
        ConfigFile=".github/workflows/buildConfig.json"
        DefaultJDK=11
        javaVersion=$(jq -r ".\"${{ inputs.project-name }}\".config.java.version // ${DefaultJDK}" $ConfigFile)
        echo "java-version=$javaVersion" >> $GITHUB_ENV
        echo "JavaVersion set to $javaVersion"

    - name: Build
      uses: addnab/docker-run-action@v3
      with:
        image: "virtuslab/scala-community-build-project-builder:jdk${{ env.java-version }}-v0.1.2"
        options: -v ${{ github.workspace }}:/opencb/
        run: |
          ConfigFile="/opencb/.github/workflows/buildConfig.json"
          DefaultConfig='{"memoryRequestMb":4096}'
          config () { 
            path=".\"${{ inputs.project-name }}\"$@" 
            jq -c -r "$path" $ConfigFile 
          }

          touch build-logs.txt  build-summary.txt
          # Assume failure unless overwritten by a successful build
          echo 'failure' > build-status.txt 


          /build/build-revision.sh \
            "$(config .repoUrl)" \
            "$(config .revision)" \
            "${{ inputs.scala-version }}" \
            '' \
            "$(config .targets)" \
            'https://repo1.maven.org/maven2' \
            '1.6.2' \
            "$(config .config // ${DefaultConfig})" 2>&1 | tee build-logs.txt

          # Store results
          mv build-logs.txt /opencb/
          mv build-status.txt /opencb/
          mv build-summary.txt /opencb

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.project-name }}
        path: ${{ github.workspace }}/build-*.txt

    - name: Check results
      shell: bash
      run: |
        # Set the result of the build
        [ "$(cat build-status.txt)" = "success" ]

