name: "Build projects"
description: "Used to build a project withing the Open Community Build"
inputs:
  project-name:
    description: "Name of the project to build"
    required: true
  scala-version:
    description: "Scala Version to use"
    required: true
  extra-scalac-options:
    description: "List of scalacOptions which should be used when building projects. Multiple entires should be seperated by a single comma character `,`"
    default: ""
  disabled-scalac-options:
    description: "List of scalacOptions which should be filted out when building projects."
    default: ""
  extra-library-dependencies:
    description: "List of library dependencies which should be injected when building projects, in format org:artifact:version or org::artifact:version for Scala cross version. Multiple entires should be seperated by a single semicolon character `;`"
    default: ""
  execute-tests:
    descriptions: "Should tests of the projects be executed"
    default: false
  custom-build-id:
    description: "Custom buildId to use instead of autogenerated github job id"
    default: ""
  # Infrastructure inputs / secrets
  maven-repo-url:
    description: "Custom Maven repository used to store artifacts"
    required: true
  elastic-user:
    description: "Secret with auth user to elasticsearch"
    required: true
  elastic-password:
    description: "Secret with auth token to elasticsearch"
    required: true
  workflow-name:
    description: "Name of the calling workflow, used to resolve build URL. Leave empty to use default (execute-build-plan / {{github.job}} (<project-name>))"
    default: ""
  container-registry:
     description: "Container registry to use"
     default: ghcr.io
  container-registry-username:
    description: "Container registry username"
    required: true
  container-registry-token:
    description: "Container registry password"
    required: true
  akka-repository-token:
    description: "Token providing access to Akka Maven repositories"
    required: false

runs:
  using: "composite"
  steps:
    - uses: coursier/cache-action@v6.4
    - uses: coursier/setup-action@v1
      with:
        apps: cs

    - name: Check java version
      shell: bash
      run: |
        ConfigFile=".github/workflows/buildConfig.json"
        DefaultJDK=17
        javaVersion=$(jq -r ".\"${{ inputs.project-name }}\".config.java.version // ${DefaultJDK}" $ConfigFile)
        if [[ $javaVersion -ge 21 && "$scalaVersion" = 3.[0-2].* ]]; then
          echo "Force Java 17, Java 21 is only supported since 3.3.x"
          javaVersion=17
        fi
        echo "java-version=$javaVersion" >> $GITHUB_ENV
        echo "JavaVersion set to $javaVersion"

    - name: Check can skip build
      id: check-history
      shell: bash
      run: |
        ConfigFile=".github/workflows/buildConfig.json"
        URL="https://scala3.westeurope.cloudapp.azure.com/data/project-build-summary/_search"
        source project-builder/versions.sh

        scalaVersion="${{ inputs.scala-version }}"

        canSkip=false
        publishScalaVersion="$(jq -r ".\"${{ inputs.project-name }}\".publishedScalaVersion" $ConfigFile)"
        if [[ "$publishScalaVersion" != "null" ]] && isBinVersionGreaterThan "$publishScalaVersion" "$scalaVersion" ; then
          echo "Can skip build: project published with $publishScalaVersion - cannot guarantee it would work with older Scala version $scalaVersion"
          canSkip=true
        else 
          echo "No reason to skip becouse of Scala version: published with: $publishScalaVersion, building with $scalaVersion"
        fi 
        
        if [[ "$canSkip" == false ]]; then
          if [[ -n "${{ inputs.extra-scalac-options }}" || -n "${{ inputs.disabled-scalac-options }}" ]]; then
            echo "Using custom scalacOption, cannot skip"
          elif [[ -n "${{ inputs.custom-build-id }}" ]]; then
            echo "Using custom build id, won't skip"
          else
            projectName="${{ inputs.project-name }}"
            projectVersion="$(jq -r ".\"${{ inputs.project-name }}\".version" $ConfigFile)"
              
            # Elasticsearch query JSON
            query='
            {
              "_source": ["projectName", "scalaVersion", "version", "status"],
              "query": {
                "bool": {
                  "must": [
                    { "term": { "projectName": "'$projectName'" } },
                    { "term": { "scalaVersion": "'"$scalaVersion"'" } },
                    { "term": { "version": "'"$projectVersion"'" } }
                  ]
                }
              }
            }'

            # Make the request to Elasticsearch
            response=$(curl -s -u ${{ inputs.elastic-user }}:${{ inputs.elastic-password }} -XPOST -H "Content-Type: application/json" -d "$query" "$URL")

            # Check if the request was successful
            if [ "$(echo "$response" | jq -r '.error')" != "null" ]; then
              echo "Error: Failed to fetch data from Elasticsearch."
              echo "$response"
            else 
              echo "$response" | jq -r '.hits.hits'
              canSkip=$(echo "$response" | jq -r 'any(.hits.hits[]; ._source.status == "success")')
            fi
          fi
        fi
        echo "Can skip build: $canSkip"
        echo "can-skip-build=${canSkip}" >> $GITHUB_OUTPUT
    
    - name: Build project
      uses: WojciechMazur/docker-run-action@1.0.0
      if: steps.check-history.outputs.can-skip-build != 'true'
      with:
        registry: ${{ inputs.container-registry }}
        username: ${{ inputs.container-registry-username }}
        password: ${{ inputs.container-registry-token }}
        image: "ghcr.io/virtuslab/scala-community-build-project-builder:jdk${{ env.java-version }}-latest"
        options: >-
          -v ${{ github.workspace }}:/opencb/
          -e PROJECT_NAME=${{ inputs.project-name }}
          -e SCALA_VERSION=${{ inputs.scala-version }}
          -e MAVEN_REPO_URL=${{ inputs.maven-repo-url }}
          -e EXECUTE_TESTS=${{ inputs.execute-tests }}
          -e AKKA_REPO_TOKEN=${{ inputs.akka-repository-token }}
          -e EXTRA_SCALAC_OPTIONS=${{ inputs.extra-scalac-options }}
          -e DISABLED_SCALAC_OPTIONS=${{ inputs.disabled-scalac-options }}
          -e EXTRA_LIBRARY_DEPENDENCIES=${{ inputs.extra-library-dependencies }}
          -e OPENCB_ROOT=/opencb
          -e TIMEOUT_SECONDS=7200
        shell: bash
        run: bash /opencb/.github/actions/build-project/build.sh
    
    - name: Check status
      id: check-status
      shell: bash
      if: always() && steps.check-history.outputs.can-skip-build != 'true'
      run: echo "status=$(cat build-status.txt)" >> $GITHUB_OUTPUT

    - name: Get current job URL
      id: job-info
      if: always() && steps.check-status.outputs.status != 'success'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        GITHUB_API="repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs"
        JOB_NAME="execute-build-plan / ${{ github.job }} (${{ inputs.project-name }})"
        if [[ "${{ inputs.workflow-name }}" != "" ]]; then
          JOB_NAME="${{ inputs.workflow-name }}"
        fi
        PARAMS="?per_page=100"
        SELECT_URL=".jobs | map(select(.name == \"${JOB_NAME}\")) | .[0].html_url"

        set -o pipefail

        outFile="gh.out"
        buildURL=""
        for i in $(seq 1 10) ;do
          if gh api "${GITHUB_API}${PARAMS}" --paginate --jq "${SELECT_URL}" 2>&1 | tee $outFile; then 
            buildURL="$(cat $outFile | xargs)"
            break
          elif grep -q 'API rate limit exceeded' "$outFile"; then
            echo "GitHub API rate limit exceeded, skip resolving build URL"
            break
          elif grep -q 'Server Error (HTTP 502)' "$outFile"; then
            echo "Server error when resolving build URL, retry with backoff"
            sleep 5
          else 
            echo "Unknown error when resolving build URL:"
            cat $outFile
            break
          fi
        done  

        echo "Build URL: $buildURL"
        echo "build-url=${buildURL}" >> $GITHUB_OUTPUT

    - name: Index results
      uses: WojciechMazur/docker-run-action@1.0.0
      if: always() && steps.check-history.outputs.can-skip-build != 'true'
      with:
        registry: ${{ inputs.container-registry }}
        username: ${{ inputs.container-registry-username }}
        password: ${{ inputs.container-registry-token }}
        image: "ghcr.io/virtuslab/scala-community-build-project-builder:jdk17-latest"
        options: >-
          -v ${{ github.workspace }}:/opencb/
          -e PROJECT_NAME=${{ inputs.project-name }}
          -e SCALA_VERSION=${{ inputs.scala-version }}
          -e ELASTIC_USERNAME=${{ inputs.elastic-user }}
          -e ELASTIC_PASSWORD=${{ inputs.elastic-password }}
          -e CONTAINER_REGISTRY_TOKEN_SECRET=${{ inputs.container-registry-token }}
          -e AKKA_REPOSITORY_TOKEN_SECRET=${{ inputs.akka-repository-token }}
          -e BUILD_ID=${{ inputs.custom-build-id != '' && inputs.custom-build-id || github.run_id }}
          -e BUILD_URL=${{ steps.job-info.outputs.build-url }}
          -e OPENCB_ROOT=/opencb
        shell: bash
        run: bash /opencb/.github/actions/build-project/index.sh

    - name: Check results
      shell: bash
      if: always() && steps.check-history.outputs.can-skip-build != 'true'
      run: |
        # Set the result of the build
        if [[ "${{ steps.check-status.outputs.status }}" == "success" ]]; then 
          echo "Build successful"
        else 
          echo "Build failure! Check logs for details"
          exit 1
        fi
