name: "Build projects"
description: "Used to build a project withing the Open cOmunityu Build"
inputs:
  project-name:
    description: "Name of the project to build"
    required: true
  scala-version:
    description: "Scala Version to use"
    required: true
runs:
  using: "composite"
  steps:
    - name: Check java version
      shell: bash
      run: |
        ConfigFile=".github/workflows/buildConfig.json"
        DefaultJDK=11
        javaVersion=$(jq -r ".\"${{ inputs.project-name }}\".config.java.version // ${DefaultJDK}" $ConfigFile)
        echo "java-version=$javaVersion" >> $GITHUB_ENV
        echo "JavaVersion set to $javaVersion"

    - name: Prepare output files
      shell: bash
      run: |
        touch build-logs.txt  build-summary.txt
        # Assume failure unless overwritten by a successful build
        echo 'failure' > build-status.txt 

    - name: Build
      uses: addnab/docker-run-action@v3
      with:
        image: "virtuslab/scala-community-build-project-builder:jdk${{ env.java-version }}-v0.1.2"
        options: -v ${{ github.workspace }}:/opencb/
        run: |
          set -x
          ConfigFile="/opencb/.github/workflows/buildConfig.json"
          config () { 
            jq -c -r ".\"${{ inputs.project-name }}\"$1" $ConfigFile 
          }

          /build/build-revision.sh \
            "$(config .repoUrl)" \
            "$(config .revision)" \
            "${{ inputs.scala-version }}" \
            '' \
            "$(config .targets)" \
            'https://repo1.maven.org/maven2' \
            '1.6.2' \
            "$(config .config)" 2>&1 | tee build-logs.txt
          
          # Store results
          mv build-logs.txt /opencb/
          mv build-status.txt /opencb/
          mv build-summary.txt /opencb
          
          # Set the result of the build
          [ "$(cat build-status.txt)" = "success" ]


    - name: Check results
      shell: bash
      run: |
        set -x
        ls -l
        cat build-status.txt
        cat build-summary.txt
        cat build-logs.txt

