//> using scala "3.2"
//> using lib "com.novocode:junit-interface:0.11"
//> using lib "org.jsoup:jsoup:1.16.1"
//> using lib "org.json4s::json4s-native:4.0.6"
//> using lib "org.json4s::json4s-ext:4.0.6"
//> using lib "com.github.pureconfig::pureconfig-core:0.17.4"
//> using lib "com.lihaoyi::os-lib:0.9.1"
//> using lib "com.lihaoyi::requests:0.8.0"

//> using resourceDir "../resources"
