//> using scala "3.3"
//> using dep "com.novocode:junit-interface:0.11"
//> using dep "org.jsoup:jsoup:1.17.2"
//> using dep "org.json4s::json4s-native:4.0.7"
//> using dep "org.json4s::json4s-ext:4.0.7"
//> using dep "com.github.pureconfig::pureconfig-core:0.17.7"
//> using dep "com.lihaoyi::os-lib:0.10.2"
//> using dep "com.lihaoyi::requests:0.8.3"

//> using resourceDir "../resources"
