
# projects total:     6
# min stars count:    -1
# max projects count: 1000

name: "Execute Open Community Build plan"
on:
  workflow_call:
    inputs:
      published-scala-version:
        type: string
        description: 'Published Scala version to use, if empty new version of compiler would be build with default name based on the selected repository'
      repository-url:
        type: string
        description: "GitHub repository URL for compiler to build, ignored when published-scala-version is defined"
        default: "scala/scala3"
      repository-branch:
        type: string
        description: "GitHub repository branch for compiler to build, ignored when published-scala-version is defined"
        default: "main"
      extra-scalac-options:
        type: string
        description: "List of scalacOptions which should be used when building projects. Multiple entires should be seperated by a single comma character `,`"
        default: ""
      disabled-scalac-options:
        type: string
        description: "List of scalacOptions which should be filtered out when building projects."
        default: ""
      extra-library-dependencies:
        type: string
        description: "List of library dependencies which should be injected when building projects, in format org:artifact:version, or org::artifact:version for Scala cross version. Multiple entires should be seperated by a single semicolon character `;`. (Best effort)"
        default: ""
      custom-build-id:
        type: string
        description: "Custom buildId to use instead of autogenerated github job id"
        default: ""
    outputs:
      used-scala-version:
        description: "Version of Scala used to run the build"
        value: ${{ jobs.setup-build.outputs.scala-version }}
    secrets:
      OPENCB_ELASTIC_USER:
        required: true
      OPENCB_ELASTIC_PSWD:
        required: true

jobs:
  setup-build:
    runs-on: ubuntu-22.04
    continue-on-error: false
    outputs:
      scala-version:  ${{ steps.setup.outputs.scala-version }}
      maven-repo-url: ${{ steps.setup.outputs.maven-repo-url }}
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v4
      - name: "Setup build"
        uses: ./.github/actions/setup-build
        id: setup
        with:
          scala-version: ${{ inputs.published-scala-version }}
          repository-url: ${{ inputs.repository-url }}
          repository-branch: ${{ inputs.repository-branch }}

  stage-0:
    runs-on: ubuntu-22.04
    needs: [ setup-build ]
    continue-on-error: true
    timeout-minutes: 360
    strategy:
      matrix:
        include:
        - name: "epfl-lara/lisa"
        - name: "lichess-org/lila"
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v4
      - name: "Build project"
        uses: ./.github/actions/build-project
        timeout-minutes: 360
        with:
          project-name: ${{ matrix.name }}
          custom-build-id: ${{ inputs.custom-build-id }}
          extra-scalac-options: ${{ inputs.extra-scalac-options }}
          disabled-scalac-options: ${{ inputs.disabled-scalac-options }}
          extra-library-dependencies: ${{ inputs.extra-library-dependencies }}
          scala-version: ${{ needs.setup-build.outputs.scala-version }}
          maven-repo-url: ${{ needs.setup-build.outputs.maven-repo-url }}
          elastic-user: ${{ secrets.OPENCB_ELASTIC_USER }}
          elastic-password: ${{ secrets.OPENCB_ELASTIC_PSWD }}
  stage-1:
    runs-on: ubuntu-22.04
    needs: [ setup-build ]
    continue-on-error: true
    timeout-minutes: 360
    strategy:
      matrix:
        include:
        - name: "gvolpe/trading"
        - name: "lichess-org/lila-ws"
        - name: "lichess-org/playframework-lila"
        - name: "lichess-org/scalachess"
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v4
      - name: "Build project"
        uses: ./.github/actions/build-project
        timeout-minutes: 60
        with:
          project-name: ${{ matrix.name }}
          custom-build-id: ${{ inputs.custom-build-id }}
          extra-scalac-options: ${{ inputs.extra-scalac-options }}
          disabled-scalac-options: ${{ inputs.disabled-scalac-options }}
          extra-library-dependencies: ${{ inputs.extra-library-dependencies }}
          scala-version: ${{ needs.setup-build.outputs.scala-version }}
          maven-repo-url: ${{ needs.setup-build.outputs.maven-repo-url }}
          elastic-user: ${{ secrets.OPENCB_ELASTIC_USER }}
          elastic-password: ${{ secrets.OPENCB_ELASTIC_PSWD }}
