name: "Open CB: bisect"
run-name: ${{ inputs.build-name != '' && inputs.build-name || format('{0} - Scala {1} @ {2} / {3} {4}{5}', inputs.project-name, inputs.published-scala-version != '' && inputs.published-scala-version || 'snapshot', inputs.repository-url, inputs.repository-branch, inputs.extra-scalac-options != '' && format('extraScalacOptions={0} ', inputs.extra-scalac-options) || '', inputs.disabled-scalac-options != '' && format('disabledScalacOptions={0}', inputs.disabled-scalac-options) || '' ) }}

on:
  workflow_dispatch:
    inputs:
      build-name:
        type: string
        description: "Custom name of the job in GitHub Actions"
        default: ""
      project-name:
        type: string
        description: "Name of a project to build using GitHub coordinates <org>/<repo> eg. VirtusLab/scala-cli"
      repository-url:
        type: string
        description: "GitHub repository URL for compiler to build, ignored when published-scala-version is defined"
        default: "lampepfl/dotty"
      scala-version-start:
        type: string
        description: "The first version of Scala versions range to test against"
        default: ""
      scala-version-end:
        type: string
        description: "The last version of Scala versions range to test against"
        default: ""
      extra-scalac-options:
        type: string
        description: "List of scalacOptions which should be used when building projects. Multiple entires should be seperated by a single comma character `,`"
        default: ""
      disabled-scalac-options:
        type: string
        description: "List of scalacOptions which should be filtered out when building projects."
        default: ""
jobs:
  run-bisect:
    runs-on: ubuntu-22.04
    continue-on-error: false
    timeout-minutes: 60
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository-url }}
          ref: main
          path: "compiler"
      - uses: coursier/cache-action@v6.4

      - name: Check java version
        shell: bash
        run: |
          ConfigFile=".github/workflows/buildConfig.json"
          DefaultJDK=11
          javaVersion=$(jq -r ".\"${{ inputs.project-name }}\".config.java.version // ${DefaultJDK}" $ConfigFile)
          echo "java-version=$javaVersion" >> $GITHUB_ENV
          echo "JavaVersion set to $javaVersion"


      - name: "Build project"
        uses: ./.github/actions/build-project
        with:
          project-name: ${{ inputs.project-name }}
          extra-scalac-options: ${{ inputs.extra-scalac-options }}
          disabled-scalac-options: ${{ inputs.disabled-scalac-options }}
          scala-version: ${{ needs.setup-build.outputs.scala-version }}
          maven-repo-url: https://scala3.westeurope.cloudapp.azure.com/maven2/bisect/
          elastic-user: ${{ secrets.OPENCB_ELASTIC_USER }}
          elastic-password: ${{ secrets.OPENCB_ELASTIC_PSWD }}
          github-key: ${{ secrets.OPENCB_GITHUB_KEY }}
