
# projects total:     108
# min stars count:    -1
# max projects count: 1000

name: "Execute Open Community Build plan"
on:
  workflow_call:
    inputs:
      published-scala-version:
        type: string
        description: 'Published Scala version to use, if empty new version of compiler would be build with default name based on the selected repository'
      repository-url:
        type: string
        description: "GitHub repository URL for compiler to build, ignored when published-scala-version is defined"
        default: "lampepfl/dotty"
      repository-branch:
        type: string
        description: "GitHub repository branch for compiler to build, ignored when published-scala-version is defined"
        default: "main"
      extra-scalac-options:
        type: string
        description: "List of scalacOptions which should be used when building projects. Multiple entires should be seperated by a single comma character `,`"
        default: ""
      disabled-scalac-options:
        type: string
        description: "List of scalacOptions which should be filtered out when building projects."
        default: ""
      custom-build-id:
        type: string
        description: "Custom buildId to use instead of autogenerated github job id"
        default: ""
    outputs:
      used-scala-version:
        description: "Version of Scala used to run the build"
        value: ${{ jobs.setup-build.outputs.scala-version }}
    secrets:
      OPENCB_ELASTIC_USER:
        required: true
      OPENCB_ELASTIC_PSWD:
        required: true

jobs:
  setup-build:
    runs-on: ubuntu-22.04
    continue-on-error: false
    outputs:
      scala-version:  ${{ steps.setup.outputs.scala-version }}
      maven-repo-url: ${{ steps.setup.outputs.maven-repo-url }}
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v3
      - name: "Setup build"
        uses: ./.github/actions/setup-build
        id: setup
        with:
          scala-version: ${{ inputs.published-scala-version }}
          repository-url: ${{ inputs.repository-url }}
          repository-branch: ${{ inputs.repository-branch }}

  stage-0:
    runs-on: ubuntu-22.04
    needs: [ setup-build ]
    continue-on-error: true
    timeout-minutes: 360
    strategy:
      matrix:
        include:
        - name: "nickburkard/aws-cdk-scala"
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v3
      - name: "Build project"
        uses: ./.github/actions/build-project
        timeout-minutes: 360
        with:
          project-name: ${{ matrix.name }}
          custom-build-id: ${{ inputs.custom-build-id }}
          extra-scalac-options: ${{ inputs.extra-scalac-options }}
          disabled-scalac-options: ${{ inputs.disabled-scalac-options }}
          scala-version: ${{ needs.setup-build.outputs.scala-version }}
          maven-repo-url: ${{ needs.setup-build.outputs.maven-repo-url }}
          elastic-user: ${{ secrets.OPENCB_ELASTIC_USER }}
          elastic-password: ${{ secrets.OPENCB_ELASTIC_PSWD }}
  stage-1:
    runs-on: ubuntu-22.04
    needs: [ setup-build ]
    continue-on-error: true
    timeout-minutes: 360
    strategy:
      matrix:
        include:
        - name: "abdolence/circe-tagged-adt-codec"
        - name: "adampingel/axle-cicd"
        - name: "alexandru/alexandru"
        - name: "alexarchambault/scalacon-2022-demo"
        - name: "alexarchambault/scalacon2022-demo"
        - name: "apache/logging-log4j-scala"
        - name: "aptusproject/aptus-core"
        - name: "armanbilge/circe"
        - name: "beangle/commons"
        - name: "carlos-verdes/funkode"
        - name: "caspercommunityio/casper-scala-sdk"
        - name: "cchantep/play-reactivemongo"
        - name: "clulab/scala-transformers"
        - name: "com-lihaoyi/ammonite"
        - name: "coursier/dependency"
        - name: "dacr/lorem-ipsum"
        - name: "dataoperandz/cassper"
        - name: "davidledwards/zookeeper"
        - name: "dmurvihill/courier"
        - name: "dmytromitin/dotty-patched"
        - name: "e257-fi/dirsuite"
        - name: "eclipse-pass/pass-java-client"
        - name: "eed3si9n/sbt-coursier"
        - name: "emartech/escher-akka-http"
        - name: "errors4s/errors4s-core-circe"
        - name: "es-meta/esmeta"
        - name: "finos/morphir-scala"
        - name: "guardian/support-frontend"
        - name: "gzoller/scala-reflection"
        - name: "iltotore/iron"
        - name: "jcouyang/meow"
        - name: "jphmrst/scala-outlines"
        - name: "jsfwa/zio-cassandra"
        - name: "kag0/ninny-json"
        - name: "kailuowang/pencil"
        - name: "karazinscalausersgroup/circe-literal-extras"
        - name: "kevin-lee/can-equal"
        - name: "kevin-lee/extras"
        - name: "kevin-lee/just-fp"
        - name: "labra/srdf"
        - name: "line/armeria"
        - name: "lorandszakacs/sprout"
        - name: "makenowjust-labs/lite"
        - name: "mbari-org/commons"
        - name: "mdedetrich/scalajson"
        - name: "mixql/mixql-platform-demo"
        - name: "mpollmeier/scala-repl-pp"
        - name: "msgpack4z/msgpack4z-native"
        - name: "nafg/dialogue-state"
        - name: "neandertech/jsonrpclib"
        - name: "nrinaudo/kantan.repl"
        - name: "nrktkt/ninny-json"
        - name: "oleg-py/shironeko"
        - name: "openlink/virtuoso-opensource"
        - name: "outr/testy"
        - name: "oyvindberg/bleep"
        - name: "oyvindberg/tui-scala"
        - name: "oyvindberg/typo"
        - name: "pdal/java"
        - name: "percontmx/cfdi"
        - name: "pityka/aten-scala"
        - name: "pjfanning/scala3-reflection"
        - name: "primetalk/typed-ontology"
        - name: "quafadas/scautable"
        - name: "rmgk/slips"
        - name: "rocketfuel/sdbc"
        - name: "rssh/scala-gopher"
        - name: "sbrunk/tokenizers-scala"
        - name: "scala-js/scala-js-macrotask-executor"
        - name: "sciss/processor"
        - name: "sciss/scala-chart"
        - name: "sciss/serial"
        - name: "sciss/swingplus"
        - name: "sdrafahl/migratepipeline"
        - name: "sensorsdata/sa-sdk-android-plugin2"
        - name: "simy4/xpath-to-xml"
        - name: "stryker-mutator/mutation-testing-elements"
        - name: "tabdulradi/mazboot"
        - name: "thinkingdataanalytics/android-sdk"
        - name: "tinkoff/oolong"
        - name: "troungtam70/wezterm"
        - name: "vigoo/zio-aws"
        - name: "vigoo/zio-http-rust"
        - name: "virtuslab/besom"
        - name: "virtuslab/pretty-stacktraces"
        - name: "wangzaixiang/wjson"
        - name: "wireapp/wire-signals"
        - name: "xebia-functional/xef"
        - name: "xuwei-k/wartremover-scalikejdbc"
        - name: "zygfryd/scala-zygf-cement"
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v3
      - name: "Build project"
        uses: ./.github/actions/build-project
        timeout-minutes: 60
        with:
          project-name: ${{ matrix.name }}
          custom-build-id: ${{ inputs.custom-build-id }}
          extra-scalac-options: ${{ inputs.extra-scalac-options }}
          disabled-scalac-options: ${{ inputs.disabled-scalac-options }}
          scala-version: ${{ needs.setup-build.outputs.scala-version }}
          maven-repo-url: ${{ needs.setup-build.outputs.maven-repo-url }}
          elastic-user: ${{ secrets.OPENCB_ELASTIC_USER }}
          elastic-password: ${{ secrets.OPENCB_ELASTIC_PSWD }}
  stage-2:
    runs-on: ubuntu-22.04
    needs: [ setup-build, stage-1 ]
    continue-on-error: true
    timeout-minutes: 360
    strategy:
      matrix:
        include:
        - name: "beangle/boot"
        - name: "beangle/cache"
        - name: "beangle/cdi"
        - name: "beangle/data"
        - name: "beangle/template"
        - name: "beangle/web"
        - name: "kevin-lee/maven2sbt"
        - name: "pjfanning/jackson-scala3-reflection-extensions"
        - name: "pme123/camundala-dsl"
        - name: "sciss/fscape-next"
        - name: "sciss/pdflitz"
        - name: "sciss/scalainterpreterpane"
        - name: "sciss/span"
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v3
      - name: "Build project"
        uses: ./.github/actions/build-project
        timeout-minutes: 60
        with:
          project-name: ${{ matrix.name }}
          custom-build-id: ${{ inputs.custom-build-id }}
          extra-scalac-options: ${{ inputs.extra-scalac-options }}
          disabled-scalac-options: ${{ inputs.disabled-scalac-options }}
          scala-version: ${{ needs.setup-build.outputs.scala-version }}
          maven-repo-url: ${{ needs.setup-build.outputs.maven-repo-url }}
          elastic-user: ${{ secrets.OPENCB_ELASTIC_USER }}
          elastic-password: ${{ secrets.OPENCB_ELASTIC_PSWD }}
  stage-3:
    runs-on: ubuntu-22.04
    needs: [ setup-build, stage-2 ]
    continue-on-error: true
    timeout-minutes: 360
    strategy:
      matrix:
        include:
        - name: "beangle/serializer"
        - name: "beangle/webmvc"
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v3
      - name: "Build project"
        uses: ./.github/actions/build-project
        timeout-minutes: 60
        with:
          project-name: ${{ matrix.name }}
          custom-build-id: ${{ inputs.custom-build-id }}
          extra-scalac-options: ${{ inputs.extra-scalac-options }}
          disabled-scalac-options: ${{ inputs.disabled-scalac-options }}
          scala-version: ${{ needs.setup-build.outputs.scala-version }}
          maven-repo-url: ${{ needs.setup-build.outputs.maven-repo-url }}
          elastic-user: ${{ secrets.OPENCB_ELASTIC_USER }}
          elastic-password: ${{ secrets.OPENCB_ELASTIC_PSWD }}
  stage-4:
    runs-on: ubuntu-22.04
    needs: [ setup-build, stage-3 ]
    continue-on-error: true
    timeout-minutes: 360
    strategy:
      matrix:
        include:
        - name: "beangle/security"
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v3
      - name: "Build project"
        uses: ./.github/actions/build-project
        timeout-minutes: 60
        with:
          project-name: ${{ matrix.name }}
          custom-build-id: ${{ inputs.custom-build-id }}
          extra-scalac-options: ${{ inputs.extra-scalac-options }}
          disabled-scalac-options: ${{ inputs.disabled-scalac-options }}
          scala-version: ${{ needs.setup-build.outputs.scala-version }}
          maven-repo-url: ${{ needs.setup-build.outputs.maven-repo-url }}
          elastic-user: ${{ secrets.OPENCB_ELASTIC_USER }}
          elastic-password: ${{ secrets.OPENCB_ELASTIC_PSWD }}
  stage-5:
    runs-on: ubuntu-22.04
    needs: [ setup-build, stage-4 ]
    continue-on-error: true
    timeout-minutes: 360
    strategy:
      matrix:
        include:
        - name: "beangle/ems"
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v3
      - name: "Build project"
        uses: ./.github/actions/build-project
        timeout-minutes: 60
        with:
          project-name: ${{ matrix.name }}
          custom-build-id: ${{ inputs.custom-build-id }}
          extra-scalac-options: ${{ inputs.extra-scalac-options }}
          disabled-scalac-options: ${{ inputs.disabled-scalac-options }}
          scala-version: ${{ needs.setup-build.outputs.scala-version }}
          maven-repo-url: ${{ needs.setup-build.outputs.maven-repo-url }}
          elastic-user: ${{ secrets.OPENCB_ELASTIC_USER }}
          elastic-password: ${{ secrets.OPENCB_ELASTIC_PSWD }}
