
# projects total:     95
# min stars count:    -1
# max projects count: 1000

name: "Execute Open Community Build plan"
on:
  workflow_call:
    inputs:
      published-scala-version:
        type: string
        description: 'Published Scala version to use, if empty new version of compiler would be build with default name based on the selected repository'
      repository-url:
        type: string
        description: "GitHub repository URL for compiler to build, ignored when published-scala-version is defined"
        default: "scala/scala3"
      repository-branch:
        type: string
        description: "GitHub repository branch for compiler to build, ignored when published-scala-version is defined"
        default: "main"
      extra-scalac-options:
        type: string
        description: "List of scalacOptions which should be used when building projects. Multiple entires should be seperated by a single comma character `,`"
        default: ""
      disabled-scalac-options:
        type: string
        description: "List of scalacOptions which should be filtered out when building projects."
        default: ""
      extra-library-dependencies:
        type: string
        description: "List of library dependencies which should be injected when building projects, in format org:artifact:version, or org::artifact:version for Scala cross version. Multiple entires should be seperated by a single semicolon character `;`. (Best effort)"
        default: ""
      execute-tests:
        type: boolean
        description: "Should the workflow execute tests of the build projects (compile only by default)"
        default: false
      custom-build-id:
        type: string
        description: "Custom buildId to use instead of autogenerated github job id"
        default: ""
    outputs:
      used-scala-version:
        description: "Version of Scala used to run the build"
        value: ${{ jobs.setup-build.outputs.scala-version }}
    secrets:
      OPENCB_ELASTIC_USER:
        required: true
      OPENCB_ELASTIC_PSWD:
        required: true
      GHCR_TOKEN:
        required: true
      OPENCB_AKKA_REPO_TOKEN:
        required: true

jobs:
  setup-build:
    runs-on: ubuntu-22.04
    continue-on-error: false
    outputs:
      scala-version:  ${{ steps.setup.outputs.scala-version }}
      maven-repo-url: ${{ steps.setup.outputs.maven-repo-url }}
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v6
      - name: "Setup build"
        uses: ./.github/actions/setup-build
        id: setup
        with:
          scala-version: ${{ inputs.published-scala-version }}
          repository-url: ${{ inputs.repository-url }}
          repository-branch: ${{ inputs.repository-branch }}

  stage-0:
    runs-on: ubuntu-22.04
    needs: [ setup-build ]
    continue-on-error: true
    strategy:
      matrix:
        include:
        - name: "aaronp/code-template"
        - name: "ablearthy/tdjson-bind"
        - name: "alejandrohdezma/alfred4s"
        - name: "alejandrohdezma/circe-munit"
        - name: "alejandrohdezma/sbt-mdoc-toc"
        - name: "alexdupre/coinpayments-scala"
        - name: "alexdupre/thumbhash4s"
        - name: "aparo/zio-json-extra"
        - name: "augustnagro/form-url-codec"
        - name: "balmungsan/neotypes"
        - name: "beangle/doc"
        - name: "beangle/web"
        - name: "benoitlouy/tele"
        - name: "bilal-fazlani/circe-json-schema"
        - name: "bilal-fazlani/csv-schema"
        - name: "bitmarck-service/fs2-secon"
        - name: "cake-lier/tuples-space-core"
        - name: "carlos-verdes/zio-resource"
        - name: "cheleb/zio-opentelemetry-bootstrap"
        - name: "chili-piper/scala-quartz"
        - name: "cjsmith-0141/fs2-pgp"
        - name: "clockworkconsulting/csexp"
        - name: "cozydev-pink/textmogrify"
        - name: "dacr/split"
        - name: "davenverse/epimetheus-circuit"
        - name: "dragonfly-ai/img"
        - name: "dwolla/natchez-smithy4s"
        - name: "early-effect/specular"
        - name: "edadma/datetime"
        - name: "edadma/highlighter"
        - name: "edadma/hocon"
        - name: "edadma/table"
        - name: "edadma/texish"
        - name: "eikek/borer-compats"
        - name: "eikek/fit4s"
        - name: "errors4s/errors4s-http"
        - name: "estrondo/sweet-mockito"
        - name: "etorreborre/registry-scala"
        - name: "faveoled/sous-title"
        - name: "fommil/shapely"
        - name: "galliaproject/gallia-parquet"
        - name: "galliaproject/gallia-spark"
        - name: "gemini-hlsw/giapi-scala"
        - name: "gemini-hlsw/lucuma-itc"
        - name: "gemini-hlsw/lucuma-schemas"
        - name: "gzoller/deploysample"
        - name: "h8io/sbt-dependencies"
        - name: "hnaderi/portainer-client"
        - name: "hsci-r/lucene-perfieldpostingsformatordtermvectorscodec"
        - name: "hshn/slick-codegen-patch"
        - name: "hshn/yoshi"
        - name: "hshn/zlick"
        - name: "ingarabr/gcs-lock"
        - name: "ivoah/slippy"
        - name: "jamesward/zio-http-guard"
        - name: "jodersky/cronic"
        - name: "jphmrst/scalautils"
        - name: "juliano/randomuser-scala"
        - name: "kaizen-solutions/fs2-kafka-jsonschema"
        - name: "karazinscalausersgroup/mongo-literals"
        - name: "kijuky/git-for-scala"
        - name: "kirill5k/common-scala"
        - name: "krrrr38/protoquill-finagle-mysql"
        - name: "malliina/util-base"
        - name: "marcinzh/spot"
        - name: "nationalarchives/dr2-dynamo-formatters"
        - name: "natural-transformation/avocet"
        - name: "novakov-alexey/http4s-spnego"
        - name: "pablf/teseo"
        - name: "pbyrne84/scala-case-class-prettification"
        - name: "permutive-engineering/odin-contrib"
        - name: "phillhenry/dreadnought"
        - name: "pismute/classy-optics"
        - name: "pjfanning/pekko-http-session"
        - name: "pjfanning/pekko-mock-scheduler"
        - name: "pjfanning/pekko-serialization-jackson216"
        - name: "pjfanning/scala3-reflection"
        - name: "polyvariant/eds4s"
        - name: "pomadchin/dynosaur-derivation"
        - name: "quadstingray/quartz-manager"
        - name: "sadly-dubious-org/widely-used-util"
        - name: "scala-cli/java-class-name"
        - name: "scalacenter/scala3-binary-decoder"
        - name: "scalawag/sarong"
        - name: "sciss/filecache"
        - name: "sciss/optional"
        - name: "sciss/scalacollider-dot"
        - name: "sean-ideabank/rudolf"
        - name: "swagger-akka-http/swagger-scala3-enum-module"
        - name: "swaldman/conveniences"
        - name: "swaldman/failable"
        - name: "sweet-delights/delightful-typeclasses"
        - name: "vasilmkd/discipline-specs2"
        - name: "xebia-functional/munit-snap"
        - name: "zygfryd/scala-zygf-jackshaft"
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v6
      - name: "Build project"
        uses: ./.github/actions/build-project
        with:
          project-name: ${{ matrix.name }}
          custom-build-id: ${{ inputs.custom-build-id }}
          extra-scalac-options: ${{ inputs.extra-scalac-options }}
          disabled-scalac-options: ${{ inputs.disabled-scalac-options }}
          extra-library-dependencies: ${{ inputs.extra-library-dependencies }}
          execute-tests: ${{ inputs.execute-tests }}
          scala-version: ${{ needs.setup-build.outputs.scala-version }}
          maven-repo-url: ${{ needs.setup-build.outputs.maven-repo-url }}
          elastic-user: ${{ secrets.OPENCB_ELASTIC_USER }}
          elastic-password: ${{ secrets.OPENCB_ELASTIC_PSWD }}
          container-registry-username: ${{ github.actor }}
          container-registry-token: ${{ secrets.GHCR_TOKEN }}
          akka-repository-token: ${{ secrets.OPENCB_AKKA_REPO_TOKEN }}
