name: Infra CI - publish docker images

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Custom tag to publish container image version"
        required: true
jobs:
  publish-images:
    runs-on: ubuntu-22.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build all images
        run: scripts/build-all.sh ${{ inputs.version }}

      - name: Push images to GitHub Container Registry
        run: scripts/publish-all.sh ${{ inputs.version }}
