name: Community Build CLI tests

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      
      - uses: coursier/setup-action@v1
        with:
          apps: scala scala-cli sbt mill
      
      - name: Test CLI
        run: scripts/test-cli.sh
