name: Scheduled weekly build

on:
  workflow_dispatch:
  schedule:
    # Every friday at 8 PM
    - cron: "0 20 * * 5"
jobs:
  detect-version:
    runs-on: ubuntu-22.04
    continue-on-error: false
    outputs:
      last-nightly-version: ${{ steps.detect.outputs.last-nightly-version }}
      last-stable-version:  ${{ steps.detect.outputs.last-stable-version }}
      last-rc-version:      ${{ steps.detect.outputs.last-rc-version }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Install scala-cli
        uses: coursier/setup-action@v1
        with:
          apps: scala-cli

      - name: Find last versions
        id: detect
        run: |
          lastNightly="$(./scripts/lastVersionNightly.sc)"
          lastStable="$(./scripts/lastVersionStable.sc)"
          lastRC="$(./scripts/lastVersionRC.sc)" 

          echo "Detected last nightly version: $lastNightly (used)"
          echo "Detected last stable version:  $lastStable"
          echo "Detected last RC version:      $lastRC"

          echo "last-nightly-version=$lastNightly" >> $GITHUB_OUTPUT
          echo "last-stable-version=$lastStable" >> $GITHUB_OUTPUT
          echo "last-rc-version=$lastRC" >> $GITHUB_OUTPUT

  run-build:
    uses: ./.github/workflows/buildPlan.yaml
    needs: [detect-version]
    with: 
      published-scala-version: ${{ needs.detect-version.outputs.last-nightly-version }}

  create-raport:
    needs: [run-build]
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Install coursier
        uses: coursier/setup-action@v1
        with:
          apps: scala-cli
      
      - name: Generate raport
        env: 
          ES_USER: ${{ secrets.OPENCB_ELASTIC_USER }}
          ES_PASSWORD: ${{ secrets.OPENCB_ELASTIC_PSWD }}
        run: | 
          scalaVersion=${{ needs.detect-version.outputs.last-nightly-version }}
          lastRC=${{ needs.detect-version.outputs.last-rc-version }}
          lastStable=${{ needs.detect-version.outputs.last-stable-version }}

          ./scripts/raport-regressions.scala $scalaVersion > raport-full.md
          ./scripts/raport-regressions.scala $scalaVersion --compare-with $lastRC > raport-compare-$lastRC.md
          ./scripts/raport-regressions.scala $scalaVersion --compare-with $lastStable > raport-compare-$lastStable.md

      - name: Upload raports
        uses: actions/upload-artifact@v3
        with:
          name: build-raports
          path: ${{ github.workspace }}/raport-*.md


